rm -f /Users/jdenise/.m2/repository/org/apache/artemis/artemis-amqp-protocol/2.53.0/artemis-amqp-protocol-2.53.0.jar
rm -f /Users/jdenise/.m2/repository/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-process-controller/32.0.2.Final/wildfly-process-controller-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/json/bind/jakarta.json.bind-api/3.0.1/jakarta.json.bind-api-3.0.1.jar
rm -f /Users/jdenise/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-management/4.0.11/cxf-rt-management-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/glassfish/soteria/soteria/4.0.2/soteria-4.0.2.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-client/2.9.0.Final/wildfly-elytron-client-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/commons-cli/commons-cli/1.11.0/commons-cli-1.11.0.jar
rm -f /Users/jdenise/.m2/repository/org/apache/sshd/sshd-common/2.17.1/sshd-common-2.17.1.jar
rm -f /Users/jdenise/.m2/repository/io/agroal/agroal-pool/2.0/agroal-pool-2.0.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/threads/jboss-threads/3.9.2/jboss-threads-3.9.2.jar
rm -f /Users/jdenise/.m2/repository/org/jvnet/staxex/stax-ex/2.1.0/stax-ex-2.1.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-sasl-localuser/2.9.0.Final/wildfly-elytron-sasl-localuser-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-faces-mojarra/40.0.1.Final/wildfly-clustering-faces-mojarra-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/utils/2.40.17/utils-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-ws-rm/4.0.11/cxf-rt-ws-rm-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-remoting/32.0.2.Final/wildfly-remoting-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-logging/32.0.2.Final/wildfly-logging-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/metadata/jboss-metadata-web/17.1.0/jboss-metadata-web-17.1.0.jar
rm -f /Users/jdenise/.m2/repository/org/apache/lucene/lucene-queryparser/9.12.3/lucene-queryparser-9.12.3.jar
rm -f /Users/jdenise/.m2/repository/org/eclipse/angus/angus-activation/2.0.3/angus-activation-2.0.3.jar
rm -f /Users/jdenise/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.21.4/jackson-databind-2.21.4.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/activemq/artemis/integration/artemis-wildfly-integration/2.0.4.Final/artemis-wildfly-integration-2.0.4.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/services/sts/cxf-services-sts-core/4.0.11/cxf-services-sts-core-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/elytron-web/undertow-server/4.2.1.Final/undertow-server-4.2.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/openssl/wildfly-openssl-java/2.3.0.Final/wildfly-openssl-java-2.3.0.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/http-client-spi/2.40.17/http-client-spi-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/jgroups/jgroups/5.5.5.Final/jgroups-5.5.5.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-security-manager/2.9.0.Final/wildfly-elytron-security-manager-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/opensaml/opensaml-soap-api/4.3.2/opensaml-soap-api-4.3.2.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-http-external/2.9.0.Final/wildfly-elytron-http-external-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/xnio/xnio-api/3.8.16.Final/xnio-api-3.8.16.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-session-infinispan-remote/10.0.8.Final/wildfly-clustering-session-infinispan-remote-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/com/googlecode/javaewah/JavaEWAH/1.2.3/JavaEWAH-1.2.3.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-http-bearer/2.9.0.Final/wildfly-elytron-http-bearer-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/lucene/lucene-highlighter/9.12.3/lucene-highlighter-9.12.3.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-web-extension/40.0.1.Final/wildfly-clustering-web-extension-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/regions/2.40.17/regions-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/apache/activemq/activemq-artemis-native/2.0.0/activemq-artemis-native-2.0.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-webservices-server-integration/40.0.1.Final/wildfly-webservices-server-integration-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-auth-server-deprecated/2.9.0.Final/wildfly-elytron-auth-server-deprecated-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/resteasy/resteasy-client-api/7.0.2.Final/resteasy-client-api-7.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/slf4j/slf4j-api/2.0.17/slf4j-api-2.0.17.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-auth-server-http/2.9.0.Final/wildfly-elytron-auth-server-http-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/glassfish/soteria/soteria.spi.bean.decorator.weld/4.0.2/soteria.spi.bean.decorator.weld-4.0.2.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-http-stateful-basic/2.9.0.Final/wildfly-elytron-http-stateful-basic-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-security/40.0.1.Final/wildfly-security-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/bitbucket/b_c/jose4j/0.9.6/jose4j-0.9.6.jar
rm -f /Users/jdenise/.m2/repository/org/aesh/readline/2.6/readline-2.6.jar
rm -f /Users/jdenise/.m2/repository/org/projectodd/vdx/vdx-wildfly/1.1.6/vdx-wildfly-1.1.6.jar
rm -f /Users/jdenise/.m2/repository/com/github/ben-manes/caffeine/caffeine/3.2.4/caffeine-3.2.4.jar
rm -f /Users/jdenise/.m2/repository/org/hibernate/search/hibernate-search-mapper-orm/8.3.0.Final/hibernate-search-mapper-orm-8.3.0.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/ws/rs/jakarta.ws.rs-api/4.0.0/jakarta.ws.rs-api-4.0.0.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-transport-native-epoll/4.1.135.Final/netty-transport-native-epoll-4.1.135.Final-linux-aarch_64.jar
rm -f /Users/jdenise/.m2/repository/org/apache/james/apache-mime4j-core/0.8.14/apache-mime4j-core-0.8.14.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-databinding-jaxb/4.0.11/cxf-rt-databinding-jaxb-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-bindings-coloc/4.0.11/cxf-rt-bindings-coloc-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-domain-http-interface/32.0.2.Final/wildfly-domain-http-interface-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/santuario/xmlsec/3.0.6/xmlsec-3.0.6.jar
rm -f /Users/jdenise/.m2/repository/org/opensaml/opensaml-security-api/4.3.2/opensaml-security-api-4.3.2.jar
rm -f /Users/jdenise/.m2/repository/org/aesh/aesh-extensions/1.8/aesh-extensions-1.8.jar
rm -f /Users/jdenise/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.21.4/jackson-datatype-jdk8-2.21.4.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ironjacamar/ironjacamar-core-api/3.0.19.Final/ironjacamar-core-api-3.0.19.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-controller-client/32.0.2.Final/wildfly-controller-client-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/logging/jul-to-slf4j-stub/1.0.1.Final/jul-to-slf4j-stub-1.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/resteasy/resteasy-multipart-provider/7.0.2.Final/resteasy-multipart-provider-7.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-transports-http/4.0.11/cxf-rt-transports-http-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-http-client/wildfly-http-transaction-client/2.1.4.Final/wildfly-http-transaction-client-2.1.4.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-ejb-spi/40.0.1.Final/wildfly-clustering-ejb-spi-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-common/40.0.1.Final/wildfly-clustering-common-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/opensaml/opensaml-profile-api/4.3.2/opensaml-profile-api-4.3.2.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/resteasy/resteasy-jsapi/7.0.2.Final/resteasy-jsapi-7.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-http-basic/2.9.0.Final/wildfly-elytron-http-basic-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/opensaml/opensaml-xmlsec-impl/4.3.2/opensaml-xmlsec-impl-4.3.2.jar
rm -f /Users/jdenise/.m2/repository/com/carrotsearch/hppc/0.10.0/hppc-0.10.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-sasl-entity/2.9.0.Final/wildfly-elytron-sasl-entity-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-deployment-scanner/32.0.2.Final/wildfly-deployment-scanner-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-faces-api/40.0.1.Final/wildfly-clustering-faces-api-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/servlet/jsp/jakarta.servlet.jsp-api/4.0.0/jakarta.servlet.jsp-api-4.0.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-singleton-server/40.0.1.Final/wildfly-clustering-singleton-server-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ironjacamar/ironjacamar-core-impl/3.0.19.Final/ironjacamar-core-impl-3.0.19.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-jaxrs/40.0.1.Final/wildfly-jaxrs-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-transport-native-epoll/4.1.135.Final/netty-transport-native-epoll-4.1.135.Final-linux-x86_64.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-sasl-auth-util/2.9.0.Final/wildfly-elytron-sasl-auth-util-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/artemis/artemis-jdbc-store/2.53.0/artemis-jdbc-store-2.53.0.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-features-logging/4.0.11/cxf-rt-features-logging-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/apache/httpcomponents/httpmime/4.5.14/httpmime-4.5.14.jar
rm -f /Users/jdenise/.m2/repository/org/jasypt/jasypt/1.9.3/jasypt-1.9.3.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-sasl-anonymous/2.9.0.Final/wildfly-elytron-sasl-anonymous-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-bindings-soap/4.0.11/cxf-rt-bindings-soap-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/jipijapa-eclipselink/40.0.1.Final/jipijapa-eclipselink-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-server-api/10.0.8.Final/wildfly-clustering-server-api-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/mail/jakarta.mail-api/2.1.3/jakarta.mail-api-2.1.3.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/common/jboss-common-beans/2.0.1.Final/jboss-common-beans-2.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/neethi/neethi/3.2.2/neethi-3.2.2.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-resolver-dns/4.1.135.Final/netty-resolver-dns-4.1.135.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/activation/jakarta.activation-api/2.1.4/jakarta.activation-api-2.1.4.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/apache-client/2.40.17/apache-client-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/hibernate/validator/hibernate-validator/9.1.0.Final/hibernate-validator-9.1.0.Final.jar
rm -f /Users/jdenise/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.21.4/jackson-dataformat-yaml-2.21.4.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/retries-spi/2.40.17/retries-spi-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-messaging-activemq-injection/40.0.1.Final/wildfly-messaging-activemq-injection-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ws/cxf/jbossws-cxf-client/7.3.8.Final/jbossws-cxf-client-7.3.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-threads/32.0.2.Final/wildfly-threads-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-keystore/2.9.0.Final/wildfly-elytron-keystore-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-sasl/2.9.0.Final/wildfly-elytron-sasl-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-marshalling-jboss/40.0.1.Final/wildfly-clustering-marshalling-jboss-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/infinispan-hibernate-cache-spi/16.0.13/infinispan-hibernate-cache-spi-16.0.13.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-jose-util/2.9.0.Final/wildfly-elytron-jose-util-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/resteasy/resteasy-core/7.0.2.Final/resteasy-core-7.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-marshalling-protostream/10.0.8.Final/wildfly-clustering-marshalling-protostream-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/websocket/jakarta.websocket-client-api/2.2.0/jakarta.websocket-client-api-2.2.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-auth-server/2.9.0.Final/wildfly-elytron-auth-server-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/glassfish/jaxb/jaxb-runtime/4.0.8/jaxb-runtime-4.0.8.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-platform-mbean/32.0.2.Final/wildfly-platform-mbean-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-buffer/4.1.135.Final/netty-buffer-4.1.135.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-weld-ejb/40.0.1.Final/wildfly-clustering-weld-ejb-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/artemis/artemis-stomp-protocol/2.53.0/artemis-stomp-protocol-2.53.0.jar
rm -f /Users/jdenise/.m2/repository/wsdl4j/wsdl4j/1.6.3/wsdl4j-1.6.3.jar
rm -f /Users/jdenise/.m2/repository/org/hibernate/search/hibernate-search-backend-lucene/8.3.0.Final/hibernate-search-backend-lucene-8.3.0.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/profiles/2.40.17/profiles-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/hibernate/orm/hibernate-scan-jandex/7.3.2.Final/hibernate-scan-jandex-7.3.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/infinispan-clustered-counter/16.0.13/infinispan-clustered-counter-16.0.13.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/narayana/jts/narayana-jts-idlj/7.3.4.Final/narayana-jts-idlj-7.3.4.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-weld-spi/40.0.1.Final/wildfly-weld-spi-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/eclipse/yasson/3.0.4/yasson-3.0.4.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/protostream/protostream/6.0.7/protostream-6.0.7.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-pojo/40.0.1.Final/wildfly-pojo-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-xts/40.0.1.Final/wildfly-xts-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/reactivestreams/reactive-streams/1.0.4/reactive-streams-1.0.4.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/resteasy/resteasy-jackson2-provider/7.0.2.Final/resteasy-jackson2-provider-7.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-web-api/40.0.1.Final/wildfly-clustering-web-api-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-cache-infinispan-embedded/10.0.8.Final/wildfly-clustering-cache-infinispan-embedded-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-marshalling-api/40.0.1.Final/wildfly-clustering-marshalling-api-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-jpa-container-32/40.0.1.Final/wildfly-jpa-container-32-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/opensaml/opensaml-core/4.3.2/opensaml-core-4.3.2.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/msc/jboss-msc/1.5.6.Final/jboss-msc-1.5.6.Final.jar
rm -f /Users/jdenise/.m2/repository/org/eclipse/parsson/parsson/1.1.7/parsson-1.1.7.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-cache-infinispan-persistence-remote/10.0.8.Final/wildfly-clustering-cache-infinispan-persistence-remote-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/infinispan-core/16.0.13/infinispan-core-16.0.13.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-transport/4.1.135.Final/netty-transport-4.1.135.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/resteasy/resteasy-jaxb-provider/7.0.2.Final/resteasy-jaxb-provider-7.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-dynamic-ssl/2.9.0.Final/wildfly-elytron-dynamic-ssl-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-tools-wsdlto-core/4.0.11/cxf-tools-wsdlto-core-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-cache-spi/10.0.8.Final/wildfly-clustering-cache-spi-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/arns/2.40.17/arns-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/gnu/getopt/java-getopt/1.0.13/java-getopt-1.0.13.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/checksums-spi/2.40.17/checksums-spi-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-server-extension/40.0.1.Final/wildfly-clustering-server-extension-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/resteasy/resteasy-core-spi/7.0.2.Final/resteasy-core-spi-7.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/opensaml/opensaml-xacml-impl/4.3.2/opensaml-xacml-impl-4.3.2.jar
rm -f /Users/jdenise/.m2/repository/org/glassfish/jaxb/jaxb-xjc/4.0.8/jaxb-xjc-4.0.8.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/xjcplugins/cxf-xjc-boolean/4.1.3/cxf-xjc-boolean-4.1.3.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-naming-client/2.0.1.Final/wildfly-naming-client-2.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/artemis/artemis-dto/2.53.0/artemis-dto-2.53.0.jar
rm -f /Users/jdenise/.m2/repository/org/apache/velocity/velocity-engine-core/2.4.1/velocity-engine-core-2.4.1.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-sasl-scram/2.9.0.Final/wildfly-elytron-sasl-scram-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/annotation/jakarta.annotation-api/3.0.0/jakarta.annotation-api-3.0.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-io-spi/32.0.2.Final/wildfly-io-spi-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-transports-local/4.0.11/cxf-rt-transports-local-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-weld-common/40.0.1.Final/wildfly-weld-common-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ws/cxf/jbossws-cxf-transports-udp/7.3.8.Final/jbossws-cxf-transports-udp-7.3.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-installation-manager/32.0.2.Final/wildfly-installation-manager-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-jakarta-data/40.0.1.Final/wildfly-jakarta-data-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-features-clustering/4.0.11/cxf-rt-features-clustering-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-sasl-gssapi/2.9.0.Final/wildfly-elytron-sasl-gssapi-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-tools-java2ws/4.0.11/cxf-tools-java2ws-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/narayana/rts/restat-util/7.3.4.Final/restat-util-7.3.4.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-security-manager/32.0.2.Final/wildfly-security-manager-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-ws-security/4.0.11/cxf-rt-ws-security-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/jboss-iiop-client/2.0.1.Final/jboss-iiop-client-2.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/resource/jakarta.resource-api/2.1.0/jakarta.resource-api-2.1.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-ejb3/40.0.1.Final/wildfly-ejb3-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.21.4/jackson-datatype-jsr310-2.21.4.jar
rm -f /Users/jdenise/.m2/repository/io/agroal/agroal-api/2.0/agroal-api-2.0.jar
rm -f /Users/jdenise/.m2/repository/io/smallrye/reactive/mutiny/3.1.1/mutiny-3.1.1.jar
rm -f /Users/jdenise/.m2/repository/org/glassfish/jaxb/jaxb-jxc/4.0.8/jaxb-jxc-4.0.8.jar
rm -f /Users/jdenise/.m2/repository/org/projectodd/vdx/vdx-core/1.1.6/vdx-core-1.1.6.jar
rm -f /Users/jdenise/.m2/repository/org/apache/lucene/lucene-facet/9.12.3/lucene-facet-9.12.3.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-undertow/40.0.1.Final/wildfly-undertow-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/io/github/resilience4j/resilience4j-retry/2.3.0/resilience4j-retry-2.3.0.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/weld/weld-spi/6.0.Final/weld-spi-6.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-features-throttling/4.0.11/cxf-rt-features-throttling-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/narayana/rts/restat-api/7.3.4.Final/restat-api-7.3.4.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/remoting/jboss-remoting/5.0.31.Final/jboss-remoting-5.0.31.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/narayana/xts/jbossxts/7.3.4.Final/jbossxts-7.3.4.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/resteasy/resteasy-cdi/7.0.2.Final/resteasy-cdi-7.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-mechanism-gssapi/2.9.0.Final/wildfly-elytron-mechanism-gssapi-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-ssh-util/2.9.0.Final/wildfly-elytron-ssh-util-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-x500-cert-acme/2.9.0.Final/wildfly-elytron-x500-cert-acme-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.135.Final/netty-transport-native-unix-common-4.1.135.Final-osx-x86_64.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-password-impl/2.9.0.Final/wildfly-elytron-password-impl-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/slf4j/slf4j-jboss-logmanager/2.0.2.Final/slf4j-jboss-logmanager-2.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ws/jbossws-spi/5.0.0.Final/jbossws-spi-5.0.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-session-container-spi/10.0.8.Final/wildfly-clustering-session-container-spi-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-tools-wsdlto-databinding-jaxb/4.0.11/cxf-tools-wsdlto-databinding-jaxb-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/resteasy/resteasy-atom-provider/7.0.2.Final/resteasy-atom-provider-7.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/com/microsoft/azure/azure-storage/8.6.6/azure-storage-8.6.6.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/hal/hal-console/3.7.20.Final/hal-console-3.7.20.Final-resources.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-protocol/32.0.2.Final/wildfly-protocol-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/crt-core/2.40.17/crt-core-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/hibernate/models/hibernate-models/1.1.1/hibernate-models-1.1.1.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/client/wildfly-client-config/1.0.1.Final/wildfly-client-config-1.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/endpoints-spi/2.40.17/endpoints-spi-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-http-digest/2.9.0.Final/wildfly-elytron-http-digest-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/com/github/fge/msg-simple/1.1/msg-simple-1.1.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-realm/2.9.0.Final/wildfly-elytron-realm-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-server-spi/10.0.8.Final/wildfly-clustering-server-spi-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/artemis/artemis-commons/2.53.0/artemis-commons-2.53.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-permission/2.9.0.Final/wildfly-elytron-permission-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-sasl-otp/2.9.0.Final/wildfly-elytron-sasl-otp-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/httpcomponents/httpclient/4.5.14/httpclient-4.5.14.jar
rm -f /Users/jdenise/.m2/repository/io/smallrye/jandex/3.5.3/jandex-3.5.3.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-realm-jdbc/2.9.0.Final/wildfly-elytron-realm-jdbc-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/hornetq/hornetq-commons/2.4.11.Final/hornetq-commons-2.4.11.Final.jar
rm -f /Users/jdenise/.m2/repository/org/glassfish/concurro/concurro/3.1.0/concurro-3.1.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-session-cache/10.0.8.Final/wildfly-clustering-session-cache-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-subsystem/32.0.2.Final/wildfly-subsystem-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/logging/commons-logging-jboss-logging/2.0.0.Final/commons-logging-jboss-logging-2.0.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/xnio/netty/netty-xnio-transport/0.1.10.Final/netty-xnio-transport-0.1.10.Final.jar
rm -f /Users/jdenise/.m2/repository/org/hornetq/hornetq-jakarta-client/2.4.11.Final/hornetq-jakarta-client-2.4.11.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/lucene/lucene-core/9.12.3/lucene-core-9.12.3.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/weld/module/weld-jsf/6.0.4.Final/weld-jsf-6.0.4.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-request-controller/32.0.2.Final/wildfly-request-controller-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/logmanager/log4j2-jboss-logmanager/2.0.1.Final/log4j2-jboss-logmanager-2.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-jar-runtime/32.0.2.Final/wildfly-jar-runtime-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/com/fasterxml/jackson/jakarta/rs/jackson-jakarta-rs-base/2.21.4/jackson-jakarta-rs-base-2.21.4.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-rts/40.0.1.Final/wildfly-rts-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/infinispan-hibernate-cache-v66/16.0.13/infinispan-hibernate-cache-v66-16.0.13.jar
rm -f /Users/jdenise/.m2/repository/org/apache/lucene/lucene-queries/9.12.3/lucene-queries-9.12.3.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-system-jmx/40.0.1.Final/wildfly-system-jmx-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/infinispan-api/16.0.13/infinispan-api-16.0.13.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/jipijapa-hibernatesearch/40.0.1.Final/jipijapa-hibernatesearch-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/narayana/jts/narayana-jts-integration/7.3.4.Final/narayana-jts-integration-7.3.4.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-security/4.0.11/cxf-rt-security-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/auth/2.40.17/auth-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-singleton-compat/40.0.1.Final/wildfly-clustering-singleton-compat-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/validation/jakarta.validation-api/3.1.1/jakarta.validation-api-3.1.1.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-picketlink/40.0.1.Final/wildfly-picketlink-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-http-sso/2.9.0.Final/wildfly-elytron-http-sso-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-http/2.9.0.Final/wildfly-elytron-http-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/inject/jakarta.inject-api/2.0.1/jakarta.inject-api-2.0.1.jar
rm -f /Users/jdenise/.m2/repository/com/google/code/gson/gson/2.13.2/gson-2.13.2.jar
rm -f /Users/jdenise/.m2/repository/org/hibernate/common/hibernate-commons-annotations/7.0.3.Final/hibernate-commons-annotations-7.0.3.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-datasources-agroal/40.0.1.Final/wildfly-datasources-agroal-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-credential-source-impl/2.9.0.Final/wildfly-elytron-credential-source-impl-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/metadata/jboss-metadata-common/17.1.0/jboss-metadata-common-17.1.0.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-ws-mex/4.0.11/cxf-rt-ws-mex-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/elytron-web/undertow-server-servlet/4.2.1.Final/undertow-server-servlet-4.2.1.Final.jar
rm -f /Users/jdenise/.m2/repository/commons-codec/commons-codec/1.17.2/commons-codec-1.17.2.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-sasl-digest/2.9.0.Final/wildfly-elytron-sasl-digest-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-ejb-infinispan/40.0.1.Final/wildfly-clustering-ejb-infinispan-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/james/apache-mime4j-storage/0.8.14/apache-mime4j-storage-0.8.14.jar
rm -f /Users/jdenise/.m2/repository/org/hibernate/orm/hibernate-envers/7.3.2.Final/hibernate-envers-7.3.2.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/http-auth/2.40.17/http-auth-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/narayana/rts/restat-bridge/7.3.4.Final/restat-bridge-7.3.4.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/artemis/artemis-journal/2.53.0/artemis-journal-2.53.0.jar
rm -f /Users/jdenise/.m2/repository/org/opensaml/opensaml-saml-api/4.3.2/opensaml-saml-api-4.3.2.jar
rm -f /Users/jdenise/.m2/repository/org/opensaml/opensaml-xacml-saml-impl/4.3.2/opensaml-xacml-saml-impl-4.3.2.jar
rm -f /Users/jdenise/.m2/repository/jakarta/enterprise/jakarta.enterprise.lang-model/4.1.0/jakarta.enterprise.lang-model-4.1.0.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-transports-jms/4.0.11/cxf-rt-transports-jms-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/apache/commons/commons-lang3/3.20.0/commons-lang3-3.20.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-weld-jpa/40.0.1.Final/wildfly-weld-jpa-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-singleton-extension/40.0.1.Final/wildfly-clustering-singleton-extension-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-session-infinispan-embedded/10.0.8.Final/wildfly-clustering-session-infinispan-embedded-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/wss4j/wss4j-ws-security-common/3.0.5/wss4j-ws-security-common-3.0.5.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-infinispan-embedded-service/40.0.1.Final/wildfly-clustering-infinispan-embedded-service-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/com/google/guava/failureaccess/1.0.3/failureaccess-1.0.3.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/resteasy/resteasy-json-p-provider/7.0.2.Final/resteasy-json-p-provider-7.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-network/32.0.2.Final/wildfly-network-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/artemis/artemis-core-client/2.53.0/artemis-core-client-2.53.0.jar
rm -f /Users/jdenise/.m2/repository/com/github/fge/btf/1.2/btf-1.2.jar
rm -f /Users/jdenise/.m2/repository/jakarta/transaction/jakarta.transaction-api/2.0.1/jakarta.transaction-api-2.0.1.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-ee-feature-pack-product-conf/40.0.1.Final/wildfly-ee-feature-pack-product-conf-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-appclient/40.0.1.Final/wildfly-appclient-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/retries/2.40.17/retries-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/yaml/snakeyaml/2.6/snakeyaml-2.6.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-server-local/10.0.8.Final/wildfly-clustering-server-local-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/common/wildfly-common/2.0.1/wildfly-common-2.0.1.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-ejb-cache/40.0.1.Final/wildfly-clustering-ejb-cache-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/weld/module/weld-jta/6.0.4.Final/weld-jta-6.0.4.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-realm-token/2.9.0.Final/wildfly-elytron-realm-token-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/jakarta/jakarta-security/4.0.0.Final/jakarta-security-4.0.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/wss4j/wss4j-policy/3.0.5/wss4j-policy-3.0.5.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-ee-feature-pack-product-conf/40.0.1.Final/wildfly-ee-feature-pack-product-conf-40.0.1.Final-version.txt
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-jgroups-api/40.0.1.Final/wildfly-clustering-jgroups-api-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/aws-query-protocol/2.40.17/aws-query-protocol-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/eclipse/jgit/org.eclipse.jgit/7.6.0.202603022253-r/org.eclipse.jgit-7.6.0.202603022253-r.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ironjacamar/ironjacamar-common-api/3.0.19.Final/ironjacamar-common-api-3.0.19.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-naming/40.0.1.Final/wildfly-naming-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/io/undertow/ee/undertow-servlet/2.0.0.Final/undertow-servlet-2.0.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/openssl/wildfly-openssl-all/2.3.0.Final/wildfly-openssl-all-2.3.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-management-client-content/32.0.2.Final/wildfly-management-client-content-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-auth/2.9.0.Final/wildfly-elytron-auth-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/narayana/rts/restat-integration/7.3.4.Final/restat-integration-7.3.4.Final.jar
rm -f /Users/jdenise/.m2/repository/org/cryptacular/cryptacular/1.2.5/cryptacular-1.2.5.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-function/10.0.8.Final/wildfly-clustering-function-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/logging/jboss-logging/3.6.3.Final/jboss-logging-3.6.3.Final.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-transport-native-kqueue/4.1.135.Final/netty-transport-native-kqueue-4.1.135.Final-osx-aarch_64.jar
rm -f /Users/jdenise/.m2/repository/com/sun/xml/bind/external/relaxng-datatype/4.0.8/relaxng-datatype-4.0.8.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ironjacamar/ironjacamar-deployers-common/3.0.19.Final/ironjacamar-deployers-common-3.0.19.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/xjcplugins/cxf-xjc-ts/4.1.3/cxf-xjc-ts-4.1.3.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/classfilewriter/jboss-classfilewriter/1.3.1.Final/jboss-classfilewriter-1.3.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-security-saml/4.0.11/cxf-rt-security-saml-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-ws-addr/4.0.11/cxf-rt-ws-addr-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ws/projects/jaxws-undertow-httpspi/2.0.0.Final/jaxws-undertow-httpspi-2.0.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/ow2/asm/asm/9.9.1/asm-9.9.1.jar
rm -f /Users/jdenise/.m2/repository/org/apache/artemis/artemis-selector/2.53.0/artemis-selector-2.53.0.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/genericjms/generic-jms-ra-jar/3.0.0.Final/generic-jms-ra-jar-3.0.0.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/sdk-core/2.40.17/sdk-core-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-bindings-xml/4.0.11/cxf-rt-bindings-xml-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/xjcplugins/cxf-xjc-dv/4.1.3/cxf-xjc-dv-4.1.3.jar
rm -f /Users/jdenise/.m2/repository/io/github/resilience4j/resilience4j-core/2.3.0/resilience4j-core-2.3.0.jar
rm -f /Users/jdenise/.m2/repository/org/hibernate/search/hibernate-search-util-common/8.3.0.Final/hibernate-search-util-common-8.3.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/opensaml/opensaml-security-impl/4.3.2/opensaml-security-impl-4.3.2.jar
rm -f /Users/jdenise/.m2/repository/org/apache/wss4j/wss4j-ws-security-policy-stax/3.0.5/wss4j-ws-security-policy-stax-3.0.5.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/infinispan-hibernate-cache-commons/16.0.13/infinispan-hibernate-cache-commons-16.0.13.jar
rm -f /Users/jdenise/.m2/repository/io/smallrye/common/smallrye-common-function/2.17.1/smallrye-common-function-2.17.1.jar
rm -f /Users/jdenise/.m2/repository/com/google/guava/guava/33.0.0-jre/guava-33.0.0-jre.jar
rm -f /Users/jdenise/.m2/repository/org/hibernate/validator/hibernate-validator-cdi/9.1.0.Final/hibernate-validator-cdi-9.1.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-sar/40.0.1.Final/wildfly-sar-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/glassfish/jaxb/xsom/4.0.8/xsom-4.0.8.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-infinispan-extension/40.0.1.Final/wildfly-clustering-infinispan-extension-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/jipijapa-hibernate7/40.0.1.Final/jipijapa-hibernate7-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ejb3/jboss-ejb3-ext-api/2.4.0.Final/jboss-ejb3-ext-api-2.4.0.Final.jar
rm -f /Users/jdenise/.m2/repository/commons-beanutils/commons-beanutils/1.11.0/commons-beanutils-1.11.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-jsf/40.0.1.Final/wildfly-jsf-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/io/smallrye/common/smallrye-common-cpu/2.17.1/smallrye-common-cpu-2.17.1.jar
rm -f /Users/jdenise/.m2/repository/org/glassfish/jakarta.json/1.1.6/jakarta.json-1.1.6.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/metrics-spi/2.40.17/metrics-spi-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/jipijapa-spi/40.0.1.Final/jipijapa-spi-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-web-service/40.0.1.Final/wildfly-clustering-web-service-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-weld-webservices/40.0.1.Final/wildfly-weld-webservices-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-singleton-api/40.0.1.Final/wildfly-clustering-singleton-api-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/resteasy/spring/resteasy-spring/3.2.0.Final/resteasy-spring-3.2.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jberet/jberet-core/3.1.0.Final/jberet-core-3.1.0.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/http-auth-aws/2.40.17/http-auth-aws-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/mod_cluster/mod_cluster-container-spi/2.1.0.Final/mod_cluster-container-spi-2.1.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/hibernate/models/hibernate-models-jandex/1.1.1/hibernate-models-jandex-1.1.1.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-codec-dns/4.1.135.Final/netty-codec-dns-4.1.135.Final.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/infinispan-cdi-common/16.0.13/infinispan-cdi-common-16.0.13.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-security-manager-action/2.9.0.Final/wildfly-elytron-security-manager-action-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-http-cert/2.9.0.Final/wildfly-elytron-http-cert-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/s3/2.40.17/s3-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-jpa/40.0.1.Final/wildfly-jpa-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-cache-infinispan-remote/10.0.8.Final/wildfly-clustering-cache-infinispan-remote-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-marshalling-protostream/40.0.1.Final/wildfly-clustering-marshalling-protostream-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-frontend-simple/4.0.11/cxf-rt-frontend-simple-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-jsf-injection/40.0.1.Final/wildfly-jsf-injection-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/spec/jakarta/xml/soap/jboss-saaj-api_3.0_spec/1.0.0.Final/jboss-saaj-api_3.0_spec-1.0.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-util/2.9.0.Final/wildfly-elytron-util-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-mechanism-digest/2.9.0.Final/wildfly-elytron-mechanism-digest-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/glassfish/expressly/expressly/6.0.0/expressly-6.0.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-marshalling-jboss/10.0.8.Final/wildfly-clustering-marshalling-jboss-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/slf4j/jcl-over-slf4j/2.0.17/jcl-over-slf4j-2.0.17.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-cache-infinispan-persistence-jdbc/10.0.8.Final/wildfly-clustering-cache-infinispan-persistence-jdbc-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/hibernate/search/hibernate-search-backend-elasticsearch-client-rest4/8.3.0.Final/hibernate-search-backend-elasticsearch-client-rest4-8.3.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-elytron-tool-wrapper/32.0.2.Final/wildfly-elytron-tool-wrapper-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/jakarta/jakarta-client-resteasy/4.0.0.Final/jakarta-client-resteasy-4.0.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/logging/log4j/log4j-api/2.23.1/log4j-api-2.23.1.jar
rm -f /Users/jdenise/.m2/repository/com/fasterxml/jackson/jakarta/rs/jackson-jakarta-rs-json-provider/2.21.4/jackson-jakarta-rs-json-provider-2.21.4.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ws/jbossws-common/5.1.0.Final/jbossws-common-5.1.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-ejb-client/40.0.1.Final/wildfly-clustering-ejb-client-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-embedded/32.0.2.Final/wildfly-embedded-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jgroups/kubernetes/jgroups-kubernetes/3.0.0.Final/jgroups-kubernetes-3.0.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/infinispan-counter-api/16.0.13/infinispan-counter-api-16.0.13.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/remotingjmx/remoting-jmx/3.1.0.Final/remoting-jmx-3.1.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/resteasy/resteasy-client/7.0.2.Final/resteasy-client-7.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/com/fasterxml/jackson/module/jackson-module-jakarta-xmlbind-annotations/2.21.4/jackson-module-jakarta-xmlbind-annotations-2.21.4.jar
rm -f /Users/jdenise/.m2/repository/org/apache/artemis/artemis-jakarta-ra/2.53.0/artemis-jakarta-ra-2.53.0.jar
rm -f /Users/jdenise/.m2/repository/org/eclipse/angus/angus-mail/2.0.4/angus-mail-2.0.4.jar
rm -f /Users/jdenise/.m2/repository/jakarta/persistence/jakarta.persistence-api/3.2.0/jakarta.persistence-api-3.2.0.jar
rm -f /Users/jdenise/.m2/repository/org/fusesource/jansi/jansi/2.4.3/jansi-2.4.3.jar
rm -f /Users/jdenise/.m2/repository/jakarta/batch/jakarta.batch-api/2.1.1/jakarta.batch-api-2.1.1.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-sasl-oauth2/2.9.0.Final/wildfly-elytron-sasl-oauth2-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-mechanism-oauth2/2.9.0.Final/wildfly-elytron-mechanism-oauth2-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/jboss/jaxbintros/jboss-jaxb-intros/2.0.1/jboss-jaxb-intros-2.0.1.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/protocol-core/2.40.17/protocol-core-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-web-undertow/40.0.1.Final/wildfly-clustering-web-undertow-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-handler-proxy/4.1.135.Final/netty-handler-proxy-4.1.135.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/ws/xmlschema/xmlschema-core/2.3.2/xmlschema-core-2.3.2.jar
rm -f /Users/jdenise/.m2/repository/jakarta/authentication/jakarta.authentication-api/3.1.0/jakarta.authentication-api-3.1.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-client-properties/40.0.1.Final/wildfly-client-properties-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-batch-jberet/40.0.1.Final/wildfly-batch-jberet-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/lucene/lucene-analysis-common/9.12.3/lucene-analysis-common-9.12.3.jar
rm -f /Users/jdenise/.m2/repository/jakarta/enterprise/jakarta.enterprise.cdi-api/4.1.0/jakarta.enterprise.cdi-api-4.1.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-event-logger/32.0.2.Final/wildfly-event-logger-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/openjdk-orb/openjdk-orb/10.1.3.Final/openjdk-orb-10.1.3.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-sasl-external/2.9.0.Final/wildfly-elytron-sasl-external-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/jboss-vfs/3.3.2.Final/jboss-vfs-3.3.2.Final.jar
rm -f /Users/jdenise/.m2/repository/com/github/fge/jackson-coreutils/1.8/jackson-coreutils-1.8.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-realm-ldap/2.9.0.Final/wildfly-elytron-realm-ldap-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/io/smallrye/common/smallrye-common-net/2.17.1/smallrye-common-net-2.17.1.jar
rm -f /Users/jdenise/.m2/repository/de/dentrassi/crypto/pem-keystore/3.0.0/pem-keystore-3.0.0.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/staxmapper/1.5.0.Final/staxmapper-1.5.0.Final.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.135.Final/netty-transport-native-unix-common-4.1.135.Final-linux-aarch_64.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-discovery/32.0.2.Final/wildfly-discovery-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/servlet/jsp/jstl/jakarta.servlet.jsp.jstl-api/3.0.2/jakarta.servlet.jsp.jstl-api-3.0.2.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-ee-security/40.0.1.Final/wildfly-ee-security-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-marshalling-spi/10.0.8.Final/wildfly-clustering-marshalling-spi-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/metadata/jboss-metadata-appclient/17.1.0/jboss-metadata-appclient-17.1.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/jakarta/jakarta-client-webservices/4.0.0.Final/jakarta-client-webservices-4.0.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-databinding-aegis/4.0.11/cxf-rt-databinding-aegis-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/io/agroal/agroal-narayana/2.0/agroal-narayana-2.0.jar
rm -f /Users/jdenise/.m2/repository/org/aesh/aesh/2.8.4/aesh-2.8.4.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-auth-util/2.9.0.Final/wildfly-elytron-auth-util-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/metadata/jboss-metadata-ejb/17.1.0/jboss-metadata-ejb-17.1.0.jar
rm -f /Users/jdenise/.m2/repository/org/bouncycastle/bcpkix-jdk18on/1.84/bcpkix-jdk18on-1.84.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ws/cxf/jbossws-cxf-resources/7.3.8.Final/jbossws-cxf-resources-7.3.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/sshd/sshd-core/2.17.1/sshd-core-2.17.1.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-deployment-repository/32.0.2.Final/wildfly-deployment-repository-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-digest/2.9.0.Final/wildfly-elytron-digest-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/xnio/xnio-nio/3.8.16.Final/xnio-nio-3.8.16.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/json/jakarta.json-api/2.1.3/jakarta.json-api-2.1.3.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-keycloak/40.0.1.Final/wildfly-keycloak-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/weld/weld-lite-extension-translator/6.0.4.Final/weld-lite-extension-translator-6.0.4.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ironjacamar/ironjacamar-jdbc/3.0.19.Final/ironjacamar-jdbc-3.0.19.Final.jar
rm -f /Users/jdenise/.m2/repository/io/undertow/ee/undertow-websockets/2.0.0.Final/undertow-websockets-2.0.0.Final.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-transport-classes-kqueue/4.1.135.Final/netty-transport-classes-kqueue-4.1.135.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-http-oidc/2.9.0.Final/wildfly-elytron-http-oidc-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/wss4j/wss4j-ws-security-stax/3.0.5/wss4j-ws-security-stax-3.0.5.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/jboss-dmr/1.7.0.Final/jboss-dmr-1.7.0.Final.jar
rm -f /Users/jdenise/.m2/repository/com/sun/istack/istack-commons-tools/4.1.2/istack-commons-tools-4.1.2.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-wsdl/4.0.11/cxf-rt-wsdl-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/apache/artemis/artemis-server/2.53.0/artemis-server-2.53.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-credential/2.9.0.Final/wildfly-elytron-credential-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/elasticsearch/client/elasticsearch-rest-client/9.3.1/elasticsearch-rest-client-9.3.1.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-iiop-openjdk/40.0.1.Final/wildfly-iiop-openjdk-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-infinispan-client-service/40.0.1.Final/wildfly-clustering-infinispan-client-service-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-session-container-servlet-6.1/10.0.8.Final/wildfly-clustering-session-container-servlet-6.1-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/httpcomponents/httpasyncclient/4.1.5/httpasyncclient-4.1.5.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/modules/jboss-modules/2.1.6.Final/jboss-modules-2.1.6.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-auth-server-sasl/2.9.0.Final/wildfly-elytron-auth-server-sasl-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/jms/jakarta.jms-api/3.1.0/jakarta.jms-api-3.1.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-host-controller/32.0.2.Final/wildfly-host-controller-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-base/2.9.0.Final/wildfly-elytron-base-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-tools-validator/4.0.11/cxf-tools-validator-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.21.4/jackson-core-2.21.4.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-json-util/2.9.0.Final/wildfly-elytron-json-util-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/protostream/protostream-types/6.0.7/protostream-types-6.0.7.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/jakarta/jakarta-authentication/4.0.0.Final/jakarta-authentication-4.0.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-ssl/2.9.0.Final/wildfly-elytron-ssl-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/http-auth-spi/2.40.17/http-auth-spi-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/bouncycastle/bcpg-jdk18on/1.84/bcpg-jdk18on-1.84.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/aws-xml-protocol/2.40.17/aws-xml-protocol-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/infinispan-commons/16.0.13/infinispan-commons-16.0.13.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-bean-validation/40.0.1.Final/wildfly-bean-validation-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/antlr/antlr4-runtime/4.13.0/antlr4-runtime-4.13.0.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/aws-core/2.40.17/aws-core-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-infinispan-client-api/40.0.1.Final/wildfly-clustering-infinispan-client-api-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-transports-http-hc/4.0.11/cxf-rt-transports-http-hc-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.135.Final/netty-transport-native-unix-common-4.1.135.Final-linux-x86_64.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/resteasy/resteasy-rxjava2/7.0.2.Final/resteasy-rxjava2-7.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/mod_cluster/mod_cluster-core/2.1.0.Final/mod_cluster-core-2.1.0.Final.jar
rm -f /Users/jdenise/.m2/repository/net/bytebuddy/byte-buddy/1.18.8/byte-buddy-1.18.8.jar
rm -f /Users/jdenise/.m2/repository/org/opensaml/opensaml-xmlsec-api/4.3.2/opensaml-xmlsec-api-4.3.2.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/xjcplugins/cxf-xjc-bug986/4.1.3/cxf-xjc-bug986-4.1.3.jar
rm -f /Users/jdenise/.m2/repository/org/ow2/asm/asm-util/9.9.1/asm-util-9.9.1.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/resteasy/resteasy-json-binding-provider/7.0.2.Final/resteasy-json-binding-provider-7.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/com/github/fge/json-patch/1.9/json-patch-1.9.jar
rm -f /Users/jdenise/.m2/repository/com/nimbusds/nimbus-jose-jwt/10.3.1/nimbus-jose-jwt-10.3.1.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/jboss-ejb-client/5.0.8.Final/jboss-ejb-client-5.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/wss4j/wss4j-bindings/3.0.5/wss4j-bindings-3.0.5.jar
rm -f /Users/jdenise/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.21/jackson-annotations-2.21.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-domain-http-error-context/32.0.2.Final/wildfly-domain-http-error-context-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-provider-util/2.9.0.Final/wildfly-elytron-provider-util-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/resteasy/resteasy-crypto/7.0.2.Final/resteasy-crypto-7.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/spec/jakarta/xml/ws/jboss-jakarta-xml-ws-api_4.0_spec/1.0.0.Final/jboss-jakarta-xml-ws-api_4.0_spec-1.0.0.Final.jar
rm -f /Users/jdenise/.m2/repository/io/reactivex/rxjava3/rxjava/3.1.12/rxjava-3.1.12.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-weld/40.0.1.Final/wildfly-weld-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-asn1/2.9.0.Final/wildfly-elytron-asn1-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/artemis/artemis-hqclient-protocol/2.53.0/artemis-hqclient-protocol-2.53.0.jar
rm -f /Users/jdenise/.m2/repository/org/apache/httpcomponents/httpcore-nio/4.4.16/httpcore-nio-4.4.16.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-mod_cluster-undertow/40.0.1.Final/wildfly-mod_cluster-undertow-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/discovery/wildfly-discovery-client/1.3.0.Final/wildfly-discovery-client-1.3.0.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/identity-spi/2.40.17/identity-spi-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-cli/32.0.2.Final/wildfly-cli-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/transaction/wildfly-transaction-client/3.0.5.Final/wildfly-transaction-client-3.0.5.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-mechanism/2.9.0.Final/wildfly-elytron-mechanism-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/interceptor/jakarta.interceptor-api/2.2.0/jakarta.interceptor-api-2.2.0.jar
rm -f /Users/jdenise/.m2/repository/org/antlr/antlr4/4.13.0/antlr4-4.13.0.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-transport-classes-epoll/4.1.135.Final/netty-transport-classes-epoll-4.1.135.Final.jar
rm -f /Users/jdenise/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1-jbossorg-1/jakarta.servlet.jsp.jstl-3.0.1-jbossorg-1.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-codec/4.1.135.Final/netty-codec-4.1.135.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-connector/40.0.1.Final/wildfly-connector-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-jgroups-extension/40.0.1.Final/wildfly-clustering-jgroups-extension-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/hibernate/search/hibernate-search-mapper-pojo-base/8.3.0.Final/hibernate-search-mapper-pojo-base-8.3.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/opensaml/opensaml-xacml-saml-api/4.3.2/opensaml-xacml-saml-api-4.3.2.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-http-form/2.9.0.Final/wildfly-elytron-http-form-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-core-management-client/32.0.2.Final/wildfly-core-management-client-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/weld/module/weld-ejb/6.0.4.Final/weld-ejb-6.0.4.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/artemis/artemis-cli/2.53.0/artemis-cli-2.53.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-mechanism-http/2.9.0.Final/wildfly-elytron-mechanism-http-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-resolver/4.1.135.Final/netty-resolver-4.1.135.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jctools/jctools-core/4.0.6/jctools-core-4.0.6.jar
rm -f /Users/jdenise/.m2/repository/io/undertow/undertow-core/2.4.1.Final/undertow-core-2.4.1.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/4.0.5/jakarta.xml.bind-api-4.0.5.jar
rm -f /Users/jdenise/.m2/repository/io/reactivex/rxjava2/rxjava/2.2.21/rxjava-2.2.21.jar
rm -f /Users/jdenise/.m2/repository/org/opensaml/opensaml-saml-impl/4.3.2/opensaml-saml-impl-4.3.2.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-jsr77/40.0.1.Final/wildfly-jsr77-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-sasl-plain/2.9.0.Final/wildfly-elytron-sasl-plain-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/eclipse/jdt/ecj/3.33.0/ecj-3.33.0.jar
rm -f /Users/jdenise/.m2/repository/commons-io/commons-io/2.16.1/commons-io-2.16.1.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-server/32.0.2.Final/wildfly-server-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/com/fasterxml/woodstox/woodstox-core/7.0.0/woodstox-core-7.0.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-version/32.0.2.Final/wildfly-version-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/io/smallrye/common/smallrye-common-constraint/2.17.1/smallrye-common-constraint-2.17.1.jar
rm -f /Users/jdenise/.m2/repository/org/apache/qpid/proton-j/0.34.1/proton-j-0.34.1.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-web-container/40.0.1.Final/wildfly-clustering-web-container-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-health/40.0.1.Final/wildfly-health-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/marshalling/jboss-marshalling/2.3.0/jboss-marshalling-2.3.0.jar
rm -f /Users/jdenise/.m2/repository/org/elasticsearch/client/elasticsearch-rest-client-sniffer/9.3.1/elasticsearch-rest-client-sniffer-9.3.1.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/jboss-transaction-spi/8.0.0.Final/jboss-transaction-spi-8.0.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/weld/module/weld-web/6.0.4.Final/weld-web-6.0.4.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-http-util/2.9.0.Final/wildfly-elytron-http-util-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-tools-common/4.0.11/cxf-tools-common-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/weld/weld-api/6.0.Final/weld-api-6.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/glassfish/jaxb/jaxb-core/4.0.8/jaxb-core-4.0.8.jar
rm -f /Users/jdenise/.m2/repository/net/shibboleth/utilities/java-support/8.0.0/java-support-8.0.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-server-service/40.0.1.Final/wildfly-clustering-server-service-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-jdr/40.0.1.Final/wildfly-jdr-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/io/smallrye/common/smallrye-common-os/2.17.1/smallrye-common-os-2.17.1.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-codec-socks/4.1.135.Final/netty-codec-socks-4.1.135.Final.jar
rm -f /Users/jdenise/.m2/repository/org/hibernate/search/hibernate-search-backend-elasticsearch/8.3.0.Final/hibernate-search-backend-elasticsearch-8.3.0.Final.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-transport-native-kqueue/4.1.135.Final/netty-transport-native-kqueue-4.1.135.Final-osx-x86_64.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/infinispan-cdi-embedded/16.0.13/infinispan-cdi-embedded-16.0.13.jar
rm -f /Users/jdenise/.m2/repository/org/bouncycastle/bcjmail-jdk18on/1.84/bcjmail-jdk18on-1.84.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-encryption/2.9.0.Final/wildfly-elytron-encryption-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/ejb/jakarta.ejb-api/4.0.1/jakarta.ejb-api-4.0.1.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ws/jbossws-api/3.0.0.Final/jbossws-api-3.0.0.Final.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.135.Final/netty-transport-native-unix-common-4.1.135.Final-osx-aarch_64.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-weld-bean-validation/40.0.1.Final/wildfly-weld-bean-validation-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-jmx/32.0.2.Final/wildfly-jmx-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/io/smallrye/common/smallrye-common-expression/2.17.1/smallrye-common-expression-2.17.1.jar
rm -f /Users/jdenise/.m2/repository/org/glassfish/jakarta.faces/4.1.7/jakarta.faces-4.1.7.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-server-infinispan/10.0.8.Final/wildfly-clustering-server-infinispan-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/com/h2database/h2/2.4.240/h2-2.4.240.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/infinispan-cachestore-remote/16.0.13/infinispan-cachestore-remote-16.0.13.jar
rm -f /Users/jdenise/.m2/repository/jakarta/servlet/jakarta.servlet-api/6.1.0/jakarta.servlet-api-6.1.0.jar
rm -f /Users/jdenise/.m2/repository/org/bouncycastle/bcprov-jdk18on/1.84/bcprov-jdk18on-1.84.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/infinispan-cachestore-jdbc-common/16.0.13/infinispan-cachestore-jdbc-common-16.0.13.jar
rm -f /Users/jdenise/.m2/repository/org/apache/james/apache-mime4j-dom/0.8.14/apache-mime4j-dom-0.8.14.jar
rm -f /Users/jdenise/.m2/repository/org/jgroups/aws/jgroups-aws/4.0.1.Final/jgroups-aws-4.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/stdio/jboss-stdio/1.1.0.Final/jboss-stdio-1.1.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/mod_cluster/mod_cluster-load-spi/2.1.0.Final/mod_cluster-load-spi-2.1.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ws/cxf/jbossws-cxf-server/7.3.8.Final/jbossws-cxf-server-7.3.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/infinispan-cachestore-jdbc/16.0.13/infinispan-cachestore-jdbc-16.0.13.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-server-jgroups/10.0.8.Final/wildfly-clustering-server-jgroups-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/json-utils/2.40.17/json-utils-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/infinispan-client-hotrod/16.0.13/infinispan-client-hotrod-16.0.13.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/third-party-jackson-core/2.40.17/third-party-jackson-core-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/unstable/api/annotation/unstable-api-annotation-classpath-indexer/1.0.2.Final/unstable-api-annotation-classpath-indexer-1.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/invocation/jboss-invocation/2.0.1.Final/jboss-invocation-2.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/spec/jakarta/el/jakarta.el-api/6.0.2.Final/jakarta.el-api-6.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/artemis/artemis-jakarta-server/2.53.0/artemis-jakarta-server-2.53.0.jar
rm -f /Users/jdenise/.m2/repository/com/sun/xml/bind/external/rngom/4.0.8/rngom-4.0.8.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-domain-management/32.0.2.Final/wildfly-domain-management-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-codec-http/4.1.135.Final/netty-codec-http-4.1.135.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/resteasy/resteasy-validator-provider/7.0.2.Final/resteasy-validator-provider-7.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-webservices-opensaml-sysconfig/40.0.1.Final/wildfly-webservices-opensaml-sysconfig-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-el-expressly/40.0.1.Final/wildfly-clustering-el-expressly-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-weld-core/40.0.1.Final/wildfly-clustering-weld-core-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-service/40.0.1.Final/wildfly-clustering-service-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-concurrency-impl-31/40.0.1.Final/wildfly-concurrency-impl-31-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-http-client/wildfly-http-ejb-client/2.1.4.Final/wildfly-http-ejb-client-2.1.4.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/enterprise/jakarta.enterprise.cdi-el-api/4.1.0/jakarta.enterprise.cdi-el-api-4.1.0.jar
rm -f /Users/jdenise/.m2/repository/com/sun/xml/messaging/saaj/saaj-impl/3.0.5/saaj-impl-3.0.5.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-weld-ejb/40.0.1.Final/wildfly-weld-ejb-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-core/4.0.11/cxf-core-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/logmanager/jboss-logmanager/2.1.19.Final/jboss-logmanager-2.1.19.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-core-security/32.0.2.Final/wildfly-core-security-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-x500-cert-util/2.9.0.Final/wildfly-elytron-x500-cert-util-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/narayana/jbosstxbridge/7.3.4.Final/jbosstxbridge-7.3.4.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/persistence-cdi-extension/40.0.1.Final/persistence-cdi-extension-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.135.Final/netty-transport-native-unix-common-4.1.135.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-controller/32.0.2.Final/wildfly-controller-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/glassfish/jaxb/txw2/4.0.8/txw2-4.0.8.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-credential-store/2.9.0.Final/wildfly-elytron-credential-store-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/websocket/jakarta.websocket-api/2.2.0/jakarta.websocket-api-2.2.0.jar
rm -f /Users/jdenise/.m2/repository/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ws/cxf/jbossws-cxf-transports-undertow/7.3.8.Final/jbossws-cxf-transports-undertow-7.3.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/marshalling/jboss-marshalling-river/2.3.0/jboss-marshalling-river-2.3.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-elytron-oidc-client-subsystem/40.0.1.Final/wildfly-elytron-oidc-client-subsystem-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ws/jbossws-common-tools/2.1.0.Final/jbossws-common-tools-2.1.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ws/cxf/jbossws-cxf-factories/7.3.8.Final/jbossws-cxf-factories-7.3.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/codehaus/woodstox/stax2-api/4.2.2/stax2-api-4.2.2.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/infinispan-cdi-remote/16.0.13/infinispan-cdi-remote-16.0.13.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-context/10.0.8.Final/wildfly-clustering-context-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/eclipse/jgit/org.eclipse.jgit.ssh.apache/7.6.0.202603022253-r/org.eclipse.jgit.ssh.apache-7.6.0.202603022253-r.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-jose-jwk/2.9.0.Final/wildfly-elytron-jose-jwk-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-elytron-integration/32.0.2.Final/wildfly-elytron-integration-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-common/4.1.135.Final/netty-common-4.1.135.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/authorization/jakarta.authorization-api/3.0.0/jakarta.authorization-api-3.0.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-web-common/40.0.1.Final/wildfly-web-common-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/io/undertow/jastow/jastow/2.3.0.Final/jastow-2.3.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-tool/2.9.0.Final/wildfly-elytron-tool-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-ejb-extension/40.0.1.Final/wildfly-clustering-ejb-extension-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/lucene/lucene-join/9.12.3/lucene-join-9.12.3.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-concurrency-spi/40.0.1.Final/wildfly-concurrency-spi-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/jakarta/jakarta-authorization/4.0.0.Final/jakarta-authorization-4.0.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-cache-caffeine/10.0.8.Final/wildfly-clustering-cache-caffeine-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/eventstream/eventstream/1.0.1/eventstream-1.0.1.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-core-management-subsystem/32.0.2.Final/wildfly-core-management-subsystem-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-mail/40.0.1.Final/wildfly-mail-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-tools-wsdlto-frontend-jaxws/4.0.11/cxf-tools-wsdlto-frontend-jaxws-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/glassfish/jaxb/codemodel/4.0.8/codemodel-4.0.8.jar
rm -f /Users/jdenise/.m2/repository/jakarta/enterprise/concurrent/jakarta.enterprise.concurrent-api/3.1.1/jakarta.enterprise.concurrent-api-3.1.1.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-http-spnego/2.9.0.Final/wildfly-elytron-http-spnego-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/hibernate/search/hibernate-search-engine/8.3.0.Final/hibernate-search-engine-8.3.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ironjacamar/ironjacamar-common-spi/3.0.19.Final/ironjacamar-common-spi-3.0.19.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/artemis/artemis-jakarta-service-extensions/2.53.0/artemis-jakarta-service-extensions-2.53.0.jar
rm -f /Users/jdenise/.m2/repository/com/sun/istack/istack-commons-runtime/4.1.2/istack-commons-runtime-4.1.2.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/resteasy/resteasy-tracing-api/2.0.1.Final/resteasy-tracing-api-2.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/metadata/jboss-metadata-ear/17.1.0/jboss-metadata-ear-17.1.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-transactions/40.0.1.Final/wildfly-transactions-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-http-client/wildfly-http-naming-client/2.1.4.Final/wildfly-http-naming-client-2.1.4.Final.jar
rm -f /Users/jdenise/.m2/repository/jakarta/data/jakarta.data-api/1.0.1/jakarta.data-api-1.0.1.jar
rm -f /Users/jdenise/.m2/repository/org/apache/artemis/artemis-hornetq-protocol/2.53.0/artemis-hornetq-protocol-2.53.0.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/weld/weld-core-impl/6.0.4.Final/weld-core-impl-6.0.4.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/launcher/wildfly-launcher/1.0.3.Final/wildfly-launcher-1.0.3.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/wss4j/wss4j-ws-security-dom/3.0.5/wss4j-ws-security-dom-3.0.5.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/infinispan-query/16.0.13/infinispan-query-16.0.13.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-patching/32.0.2.Final/wildfly-patching-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-mechanism-scram/2.9.0.Final/wildfly-elytron-mechanism-scram-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-messaging-activemq-subsystem/40.0.1.Final/wildfly-messaging-activemq-subsystem-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/artemis/artemis-jakarta-client/2.53.0/artemis-jakarta-client-2.53.0.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-x500-principal/2.9.0.Final/wildfly-elytron-x500-principal-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/com/fasterxml/classmate/1.7.1/classmate-1.7.1.jar
rm -f /Users/jdenise/.m2/repository/org/bouncycastle/bcutil-jdk18on/1.84/bcutil-jdk18on-1.84.jar
rm -f /Users/jdenise/.m2/repository/org/jgroups/azure/jgroups-azure/2.0.2.Final/jgroups-azure-2.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/com/sun/xml/fastinfoset/FastInfoset/2.1.1/FastInfoset-2.1.1.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/checksums/2.40.17/checksums-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-ws-policy/4.0.11/cxf-rt-ws-policy-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-weld-transactions/40.0.1.Final/wildfly-weld-transactions-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/services/ws-discovery/cxf-services-ws-discovery-api/4.0.11/cxf-services-ws-discovery-api-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-x500/2.9.0.Final/wildfly-elytron-x500-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ironjacamar/ironjacamar-validator/3.0.19.Final/ironjacamar-validator-3.0.19.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-service/32.0.2.Final/wildfly-service-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-server-api/40.0.1.Final/wildfly-clustering-server-api-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-sasl-gs2/2.9.0.Final/wildfly-elytron-sasl-gs2-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/opensaml/opensaml-xacml-api/4.3.2/opensaml-xacml-api-4.3.2.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/cxf-rt-frontend-jaxws/4.0.11/cxf-rt-frontend-jaxws-4.0.11.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-jgroups-spi/40.0.1.Final/wildfly-clustering-jgroups-spi-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/apache/cxf/xjc-utils/cxf-xjc-runtime/4.1.3/cxf-xjc-runtime-4.1.3.jar
rm -f /Users/jdenise/.m2/repository/io/netty/netty-handler/4.1.135.Final/netty-handler-4.1.135.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-metrics/40.0.1.Final/wildfly-metrics-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/infinispan/infinispan-clustered-lock/16.0.13/infinispan-clustered-lock-16.0.13.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-x500-cert/2.9.0.Final/wildfly-elytron-x500-cert-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/hibernate/orm/hibernate-core/7.3.2.Final/hibernate-core-7.3.2.Final.jar
rm -f /Users/jdenise/.m2/repository/com/ibm/async/asyncutil/0.1.0/asyncutil-0.1.0.jar
rm -f /Users/jdenise/.m2/repository/org/jboss/ironjacamar/ironjacamar-common-impl/3.0.19.Final/ironjacamar-common-impl-3.0.19.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-ee/40.0.1.Final/wildfly-ee-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/software/amazon/awssdk/annotations/2.40.17/annotations-2.40.17.jar
rm -f /Users/jdenise/.m2/repository/jakarta/security/enterprise/jakarta.security.enterprise-api/4.0.0/jakarta.security.enterprise-api-4.0.0.jar
rm -f /Users/jdenise/.m2/repository/joda-time/joda-time/2.12.7/joda-time-2.12.7.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/core/wildfly-io/32.0.2.Final/wildfly-io-32.0.2.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-clustering-weld-web/40.0.1.Final/wildfly-clustering-weld-web-40.0.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-http-client/wildfly-http-client-common/2.1.4.Final/wildfly-http-client-common-2.1.4.Final.jar
rm -f /Users/jdenise/.m2/repository/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-session-spi/10.0.8.Final/wildfly-clustering-session-spi-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/security/wildfly-elytron-audit/2.9.0.Final/wildfly-elytron-audit-2.9.0.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/clustering/wildfly-clustering-cache-infinispan-common/10.0.8.Final/wildfly-clustering-cache-infinispan-common-10.0.8.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/installation-manager/installation-manager-api/1.2.1.Final/installation-manager-api-1.2.1.Final.jar
rm -f /Users/jdenise/.m2/repository/org/hornetq/hornetq-core-client/2.4.11.Final/hornetq-core-client-2.4.11.Final.jar
rm -f /Users/jdenise/.m2/repository/org/wildfly/wildfly-mod_cluster-extension/40.0.1.Final/wildfly-mod_cluster-extension-40.0.1.Final.jar
