name: WildFly Windows Test Build

on:
  push:

jobs:
  quick-build:
    name: WildFly Build -Dquickly
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
      - name: Clear any possible SNAPSHOT dependencies in the local maven repository
        run: |
          LOCAL_REPO="$HOME/.m2/repository"
          echo "Cleaning SNAPSHOTS from $LOCAL_REPO"
          if [ -d "$LOCAL_REPO" ]; then find "$LOCAL_REPO" -name "*SNAPSHOT*" | xargs -I {} rm -rfv "{}"; fi
        shell: bash
      - name: Build with Maven Java 11 - ${{ matrix.os }} -Dquickly
        run: mvn -U -B -Dquickly -X -e